const playlist1 = [
    "twenty one pilots - Chlorine",
    "Alan Walker, Sabrina Carpenter & Farruko - On My Way",
    "hooligan chase - Asshole",
    "Mark Ronson feat. Miley Cyrus - Nothing Breaks Like a Heart",
        "Mabel - Don't Call Me Up",
        "Calvin Harris, Rag'n'Bone Man - Giant",
        "MACKLEMORE & RYAN LEWIS - DOWNTOWN",
        "LMFAO - Sorry For Party Rocking",
        "LMFAO - Party Rock Anthem",
        "Post Malone, Swae Lee - Sunflower",
        "benny blanco & Calvin Harris - I Found You",
        "Avicii vs Nicky Romero - I Could Be The One",
        "Avicii - Levels",
        "Maroon 5 ft. Wiz Khalifa - Payphone",
        "Post Malone - Psycho",
        "Tiësto & Dzeko ft. Preme & Post Malone - Jackie Chan",
        "Cadet x Deno - Advice",
        "Dave ft. Fredo - Funky Friday",
        "Dave - No Words (ft. MoStack)",
        "Lewis Capaldi - Someone You Loved",
        "Tom Walker - Just You and I",
        "DJ Fresh VS Jay Fay ft. Ms Dynamite - Dibby Dibby Sound",
        "5 Seconds Of Summer - Want You Back",
        "B Young - Jumanji",
        "BlocBoy JB feat. Drake - Look Alive",
        "Bruno Mars feat. Cardi B - Finesse (Remix)",
        "Calum Scott - You Are The Reason",
        "Camila Cabello - Never Be The Same",
        "CliQ feat. Alika - Wavey",
        "Craig David feat. Bastille - I Know You",
        "Demi Lovato - Tell Me You Love Me",
        "Dua Lipa - IDGAF",
        "G-Eazy & Halsey - Him & I",
        "George Ezra - Paradise",
        "Hailee Steinfeld & Alesso feat. Florida Georgia Line & watt - Let Me Go",
        "J Hus - Bouff Daddy",
        "James Arthur - Naked",
        "James Bay - Wild Love",
        "Jason Derulo feat. French Montana - Tip Toe",
        "Jax Jones feat. Ina Wroldsen - Breathe",
        "Justin Timberlake feat. Chris Stapleton - Say Something",
        "Khalid - Location"
        
        
        
  ]
  const playlist2 = [
    "Kylie Minogue - Dancing",
  "Mabel & Not3s - Fine Line",
  "Maroon 5 - Wait",
  "Marshmello & Anne-Marie - FRIENDS",
  "NF - Let You Down",
  "Not3s x Mabel - My Lover",
  "Oasis - Live Forever",
  "Paloma Faith - Guilty",
  "Pink - Beautiful Trauma",
  "Portugal. The Man - Feel It Still",
  "Post Malone feat. Ty Dolla Sign - Psycho",
  "Rag'n'Bone Man - As You Are",
  "Rak-Su feat. Wyclef Jean & Naughty Boy - Dimelo",
  "Ramz - Barking",
  "RAYE & Mr Eazi - Decline",
  "Rudimental feat. Jess Glynne, Macklemore & Dan Caplen - These Days",
  "Sam Smith - One Last Song",
  "Sigala & Paloma Faith  - Lullaby",
  "Sigrid - Strangers",
  "Stormzy feat. MNEK - Blinded By Your Grace Pt. 2",
  "SZA x Calvin Harris - The Weekend (Funk Wav Remix)",
  "Taylor Swift - ...Ready For It",
  "Tom Walker - Leave A Light On",
  "U2 - You're The Best Thing About Me",
  "Ariana Grande - One Last Time",
  "Artists For Grenfell - Bridge Over Troubled Water ",
  "Bruno Mars - That's What I Like",
  "Calvin Harris feat. Pharrell Williams, Katy Perry & Big Sean - Feels",
  "Camila Cabello - Crying In The Club",
  "Cheat Codes feat. Demi Lovato - No Promises",
  "Clean Bandit feat. Zara Larsson - Symphony",
  "David Guetta feat. Justin Bieber - 2U",
  "Disciples - On My Mind",
  "DJ Khaled feat. Justin Bieber, Quavo, Chance The Rapper & Lil Wayne - I'm The One",
  "Fifth Harmony feat. Gucci Mane - Down",
  "French Montana feat. Swae Lee - Unforgettable",
  "Future - Mask Off",
  "Hailee Steinfeld - Most Girls",
  "HAIM - Want You Back",
  "Harry Styles - Sign Of The Times",
  "J Hus - Did You See",
  "Jason Derulo feat. Nicki Minaj & Ty Dolla Sign - Swalla",
  "Jax Jones feat. Demi Lovato & Stefflon Don - Instruction",
  "Jonas Blue feat. William Singe - Mama",

  "David Guetta feat Sam Martin - Dangerous"]
  const playlist3 = [
    "DJ Fresh feat Ella Eyre - Gravity",
    
    "Ariana Grande feat. Future  - Everyday ",
    "Bruno Mars  - 24K Magic ",
    "Calvin Harris feat. Frank Ocean & Migos - - Slide ",
    "Coldplay  - Hypnotised ",
    "Dua Lipa  - Be The One ",
    "Ed Sheeran  - Castle On The Hill  ",
    "George Michael  - Fastlove Pt.1 ",
    "Jax Jones feat. RAYE  - You Don't Know Me ",
    "John Legend  - Love Me Now ",
    "Jonas Blue feat. RAYE  - By Your Side  ",
    "Julia Michaels  - Issues  ",
    "Katy Perry feat. Skip Marley  - Chained To The Rhythm ",
    "Kygo & Selena Gomez  - It Ain't Me ",
    "Little Mix  - Touch  ",
    "Lorde  - Green Light  ",
    "M.O feat. Kent Jones - Not In Love  ",
    "Machine Gun Kelly & Camila Cabello  -  Bad Things ",
    "Major Lazer feat. PARTYNEXTDOOR & Nicki Minaj)  - Run Up  ",
    "Martin Garrix & Dua Lipa  - Scared To Be Lonely ",
    "Martin Jensen  - Solo Dance ",
    "Martin Solvieg feat. Ina Wrolsden  - Places ",
    "Post Malone feat. Quavo - Congratulations  ",
    "Rae Sremmurd feat. Gucci Mane - Black Beatles ",
    "Rag n Bone Man  - Human ",
    "Rag n Bone Man  - Skin ",
    "Robbie Williams  - Love My Life ",
    "Robin Schulz & David Guetta & Cheat Codes  - Shed A Light ",
    "Sage The Gemini  - Now and Later ",
    "Sean Paul feat. Dua Lipa  - No Lie ",
    "Sigrid  - Don't Kill My Vibe ",
    "Starley  - Call On Me  ",
    "Steve Aoki & Louis Tomlinson  - Just Hold On ",
    "Stormzy  - Big For Your Boots ",
    "The Chainsmokers  - Paris ",
    "The Vamps & Matoma  - All Night ",
    "The Weeknd feat. Daft Punk  - I Feel It Coming ",
    "The Weeknd feat. Daft Punk  - Starboy ",
    "Tinie Tempah feat. Tinashe  - Text From Your Ex ",
    "Tom Zanetti feat. Sadie Ama  - You Want Me ",
    "Train  - Play That Song ",
    "Zara Larsson  - I Would Like ",
    "Zedd & Alessia Cara  - Stay  ",
    "Russ - Psycho (Pt. 2)",
    "Logic - 1-800-273-8255 ft. Alessia Cara & Khalid",
    "iSpy (feat. Lil Yachty)",
    "21 Savage - Monster",
    "Kodaline - Brother",
    "Imagine Dragons - Bad Liar",
    "Rob $tone - Chill Bill ft. J.Davis & Spooks"
  ]
  const playlist4 = [  "JP Cooper - Passport Home",
  "Katy Perry feat. Migos - Bon Appetit",
  "Kendrick Lamar - HUMBLE.",
  "Kygo & Ellie Goulding - First Time",
  "Lady Gaga - The Cure",
  "Liam Payne feat. Quavo - Strip That Down",
  "Little Mix feat. Machine Gun Kelly - No More Sad Songs",
  "Little Mix feat. Stormzy - Power",
  "Luis Fonsi & Daddy Yankee feat. Justin Bieber - Despacito (Remix)",
  "Maggie Lindemann - Pretty Girl (Cheat Codes X CADE Remix)",
  "Martin Garrix & Troye Sivan - There For You",
  "Miley Cyrus - Malibu",
  "NEIKED feat. MIMI - Call Me",
  "Niall Horan - Slow Hands",
  "Nick Jonas feat. Anne Marie & Mike Posner - Remember I Told You",
  "Olly Murs and Louisa Johnson - Unpredictable",
  "RAYE - The Line",
  "Rita Ora - Your Song",
  "Rudimental feat. James Arthur - Sun Comes  Up",
  "Selena Gomez - Bad Liar",
  "Shawn Mendes - There's Nothing Holdin' Me Back",
  "Sigala & Ella Eyre - Came Here For Love",
  "Take That - Giants",
  "The Chainsmokers & Coldplay - Something Just Like This",
  "The Weeknd - Rockin",
  "Alex Adair - Make Me Feel Better",
  "Avicii - The Nights",
  "Blonde feat Melissa Steel - I Loved You",
  "Calvin Harris feat Elli Goulding - Outside",
  "Charli XCX feat Rita Ora - Doing It",
  "Cheryl - I Dont Care",
  "Ella Henderson - Yours",
  "Flo Rida feat Sage The Gemini and Lookas",
  "Florence and the Machine  - What Kind Of Man",
  "Gorgon City feat Jennifer Hudson - Go All Night",
  "Karen Harding - Say Something",
  "Labrinth - Jealous",
  "McBusted - Air Guitar",
  "Ne-Yo - Coming With You",
  "Oliver Heldens feat KStewart - Last All  Night  Koala",
  "Philip George - Wish You Were Mine ",
  "Rixton - Wait On Me",
  "Sam Smith - Lay Me Down",
  "Sigma feat Labrinth - Higher",
  "Tchami feat Kaleem Taylor - Promesses",
  "Wretch 32 - 6 Words",
  "Ariana Grande featuring Zedd - Break Free",
  "Calvin Harris featuring John Newman - Blame",
  "Clean Bandit & Jess Glynne - Real Love",
  "David Guetta featuring Sam Martin - Lovers On The Sun",
  "Duke Dumont - Won't Look Back",
  "Fuse ODG featuring Angel - T.I.N.A.",
  "Iggy Azalea featuring Rita Ora - Black Widow",
  "Jeremih featuring YG - Don't Tell 'Em",
  "Kiesza - Giant In My Heart",
  "Lilly Wood and Robin Schulz - Prayer In C (Robin Schulz Radio Edit)",
  "Melissa Steel featuring Popcaan - Kisses For Breakfast",
  "Nicki Minaj - Anaconda",
  "Nicole Scherzinger - Your Love",
  "Parra For Cuva featuring Anna Naklab - Wicked Games",
  "Pitbull featuring John Ryan - Fireball",
  "Professor Green featuring Tori Kelly - Lullaby",
  "Sigma featuring Paloma Faith - Changing",
  "Ten Walls - Walking With Elephants",
  "The Magician featuring Years & Years - Sunlight",
  "Wankelmut & Emma Louise - My Head Is A Jungle (MK Remix)",
  "Waze & Odyssey & R. Kelly - Bump & Grind 2014 (Waze & Odyssey vs. R. Kelly)",
  "ZHU - Faded",
  "Anne Marie  - Ciao Adios "]
  const Discord = require('discord.js');
  exports.run = async(client, message) => {
      message.channel.send(playlist1)
      await message.channel.send(playlist2)
      await message.channel.send(playlist3)
      await message.channel.send(playlist4)
      
  }